### ISSUE TITLE
Question about the code you run

### ISSUE THREAD

**Issue by Wongcheukwai** [ljjcoder/inpainting#1]
Hi , sorry to leave a question like this. I saw your comment on https://github.com/blue-blue272/fewshot-CAN. And I want to ask how to run his code and how to set up the environment for this repo since there is no guidance in his README.txt.
Thanks

**Comment by ljjcoder** [comment]
1 you need to prepare the dataset 
2 modified the --dataset  default=miniImageNet_load to --dataset  miniImageNet in args_xent.py
2 modified the --load default=True to --load default=False
3 modified the path in ./torchFewShot/datasets/miniImageNet.py
run python train.py
